# Generated by Django 5.1.4 on 2025-12-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
