# Generated by Django 5.1.4 on 2025-12-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="class_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
