# Generated by Django 5.1.4 on 2025-12-07 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_class_name"),
        ("points", "0002_classmaster"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="class_name",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="class_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="points.classmaster",
            ),
        ),
    ]
